# Generated by Django 3.2.9 on 2021-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='session',
        ),
        migrations.AddField(
            model_name='url',
            name='session_key',
            field=models.CharField(default='session', max_length=128),
            preserve_default=False,
        ),
    ]
