# Generated by Django 3.2.9 on 2021-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_session_to_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='subpart',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
